In [1]:
import pandas as pd
import numpy as np

In [2]:
dataSet = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/adults/adult.dat')

## Categorical to Numerical

In [3]:
columnss = pd.Categorical(dataSet["workclass"])
dataSet["workclass"] = columnss.codes
for i in ["education", "marital-status", "occupation", "relationship", "race", "sex", "native-country", 'Lable']:
    columnss = pd.Categorical(dataSet[i])
    dataSet[i] = columnss.codes
dataSet

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Lable
0,25.0,2,226802.0,1,7.0,4,6,3,2,1,0.0,0.0,40.0,38,0
1,38.0,2,89814.0,11,9.0,2,4,0,4,1,0.0,0.0,50.0,38,0
2,28.0,1,336951.0,7,12.0,2,10,0,4,1,0.0,0.0,40.0,38,1
3,44.0,2,160323.0,15,10.0,2,6,0,2,1,7688.0,0.0,40.0,38,1
4,34.0,2,198693.0,0,6.0,4,7,1,4,1,0.0,0.0,30.0,38,0
5,63.0,4,104626.0,14,15.0,2,9,0,4,1,3103.0,0.0,32.0,38,1
6,24.0,2,369667.0,15,10.0,4,7,4,4,0,0.0,0.0,40.0,38,0
7,55.0,2,104996.0,5,4.0,2,2,0,4,1,0.0,0.0,10.0,38,0
8,65.0,2,184454.0,11,9.0,2,6,0,4,1,6418.0,0.0,40.0,38,1
9,36.0,0,212465.0,9,13.0,2,0,0,4,1,0.0,0.0,40.0,38,0
10,26.0,2,82091.0,11,9.0,4,0,1,4,0,0.0,0.0,39.0,38,0
11,48.0,2,279724.0,11,9.0,2,6,0,4,1,3103.0,0.0,48.0,38,1
12,43.0,2,346189.0,12,14.0,2,3,0,4,1,0.0,0.0,50.0,38,1
13,20.0,5,444554.0,15,10.0,4,7,3,4,1,0.0,0.0,25.0,38,0
14,43.0,2,128354.0,11,9.0,2,0,5,4,0,0.0,0.0,30.0,38,0
15,37.0,2,60548.0,11,9.0,6,6,4,4,0,0.0,0.0,20.0,38,0
16,34.0,2,107914.0,9,13.0,2,12,0,4,1,0.0,0.0,47.0,38,1
17,34.0,2,238588.0,15,10.0,4,7,3,2,0,0.0,0.0,35.0,38,0
18,25.0,2,220931.0,9,13.0,4,9,1,4,1,0.0,0.0,43.0,28,0
19,25.0,2,205947.0,9,13.0,2,9,0,4,1,0.0,0.0,40.0,38,0
20,45.0,4,432824.0,11,9.0,2,2,0,4,1,7298.0,0.0,90.0,38,1
21,22.0,2,236427.0,11,9.0,4,0,3,4,1,0.0,0.0,20.0,38,0
22,23.0,2,134446.0,11,9.0,5,6,4,2,1,0.0,0.0,54.0,38,0
23,54.0,2,99516.0,11,9.0,2,2,0,4,1,0.0,0.0,35.0,38,0
24,32.0,4,109282.0,15,10.0,4,9,1,4,1,0.0,0.0,60.0,38,0
25,46.0,5,106444.0,15,10.0,2,3,0,2,1,7688.0,0.0,38.0,38,1
26,56.0,4,186651.0,1,7.0,6,7,4,4,0,0.0,0.0,50.0,38,0
27,24.0,4,188274.0,9,13.0,4,11,1,4,1,0.0,0.0,50.0,38,0
28,23.0,1,258120.0,15,10.0,2,10,0,4,1,0.0,0.0,40.0,38,0
29,26.0,2,43311.0,11,9.0,0,3,4,4,0,0.0,0.0,40.0,38,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45192,32.0,2,211349.0,0,6.0,2,13,0,4,1,0.0,0.0,40.0,38,0
45193,22.0,2,203715.0,15,10.0,4,0,3,4,1,0.0,0.0,40.0,38,0
45194,31.0,2,292592.0,11,9.0,2,6,5,4,0,0.0,0.0,40.0,38,0
45195,29.0,2,125976.0,11,9.0,5,11,4,4,0,0.0,0.0,35.0,38,0
45196,34.0,2,204461.0,10,16.0,2,9,0,4,1,0.0,0.0,60.0,38,1
45197,54.0,2,337992.0,9,13.0,2,3,0,1,1,0.0,0.0,50.0,23,1
45198,37.0,2,179137.0,15,10.0,0,0,4,4,0,0.0,0.0,39.0,38,0
45199,22.0,2,325033.0,2,8.0,4,10,3,2,1,0.0,0.0,35.0,38,0
45200,34.0,2,160216.0,9,13.0,4,3,1,4,0,0.0,0.0,55.0,38,1
45201,30.0,2,345898.0,11,9.0,4,2,1,2,1,0.0,0.0,46.0,38,0
45202,38.0,2,139180.0,9,13.0,0,9,4,2,0,15020.0,0.0,45.0,38,1
45203,45.0,5,252208.0,11,9.0,5,0,3,4,0,0.0,0.0,40.0,38,0
45204,45.0,1,119199.0,7,12.0,0,9,4,4,0,0.0,0.0,48.0,38,0
45205,31.0,2,199655.0,12,14.0,0,7,1,3,0,0.0,0.0,30.0,38,0
45206,39.0,1,111499.0,7,12.0,2,0,5,4,0,0.0,0.0,20.0,38,1
45207,37.0,2,198216.0,7,12.0,0,12,1,4,0,0.0,0.0,40.0,38,0
45208,43.0,2,260761.0,11,9.0,2,6,0,4,1,0.0,0.0,40.0,25,0
45209,65.0,4,99359.0,14,15.0,4,9,1,4,1,1086.0,0.0,60.0,38,0
45210,43.0,5,255835.0,15,10.0,0,0,2,4,0,0.0,0.0,40.0,38,0
45211,43.0,4,27242.0,15,10.0,2,2,0,4,1,0.0,0.0,50.0,38,0
45212,32.0,2,34066.0,0,6.0,2,5,0,0,1,0.0,0.0,40.0,38,0
45213,43.0,2,84661.0,8,11.0,2,11,0,4,1,0.0,0.0,45.0,38,0
45214,32.0,2,116138.0,12,14.0,4,12,1,1,1,0.0,0.0,11.0,35,0
45215,53.0,2,321865.0,12,14.0,2,3,0,4,1,0.0,0.0,40.0,38,1
45216,22.0,2,310152.0,15,10.0,4,10,1,4,1,0.0,0.0,40.0,38,0
45217,27.0,2,257302.0,7,12.0,2,12,5,4,0,0.0,0.0,38.0,38,0
45218,40.0,2,154374.0,11,9.0,2,6,0,4,1,0.0,0.0,40.0,38,1
45219,58.0,2,151910.0,11,9.0,6,0,4,4,0,0.0,0.0,40.0,38,0
45220,22.0,2,201490.0,11,9.0,4,0,3,4,1,0.0,0.0,20.0,38,0
45221,52.0,3,287927.0,11,9.0,2,3,5,4,0,15024.0,0.0,40.0,38,1

## Fit the tree

In [4]:
from sklearn.tree import DecisionTreeClassifier

Needed_columns = ["age", "workclass", "education-num", "marital-status", "occupation", "relationship",
                  "race", "sex", "hours-per-week", "native-country"]

clf = DecisionTreeClassifier(random_state=1)

clf.fit(dataSet[Needed_columns], dataSet["Lable"])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

## Train-Test Data

In [5]:
import math
np.random.seed(1)

dataSet = dataSet.reindex(np.random.permutation(dataSet.index))
#permutation: permute rows

## AUC in Test

In [7]:
from sklearn.metrics import roc_auc_score
train_max_row = math.floor(dataSet.shape[0] * .8)
#floor: = or < 
train = dataSet.iloc[:train_max_row]
test = dataSet.iloc[train_max_row:]
model = DecisionTreeClassifier(random_state=1)
model.fit(train[Needed_columns], train["Lable"])
predictions = model.predict(test[Needed_columns])
AUC = roc_auc_score(test["Lable"], predictions)
print(AUC)

0.703419211743771

## AUC in Train

In [ ]:
predictions = model.predict(train[Needed_columns])
print(roc_auc_score(train["Lable"], predictions))

## plot Tree

In [ ]:
from sklearn import tree
import pydotplus
from IPython.display import Image

In [ ]:
dot_data = tree.export_graphviz(model, out_file=None, 
                                feature_names=Needed_columns,  
                                class_names='1,2')

graph = pydotplus.graph_from_dot_data(dot_data)  


Image(graph.create_png())

## Limit Overfit

In [ ]:
model2 = DecisionTreeClassifier(random_state=1)
model2 = DecisionTreeClassifier(min_samples_split=3, random_state=1)
model2.fit(train[Needed_columns], train["Lable"])
predictions = model2.predict(test[Needed_columns])
test_auc = roc_auc_score(test["Lable"], predictions)
train_predictions = model2.predict(train[Needed_columns])
train_auc = roc_auc_score(train["Lable"], train_predictions)
print(test_auc)
print(train_auc)

## تمرین
## Min Samples Split

In [ ]:
model2 = DecisionTreeClassifier(random_state=1)
model2 = DecisionTreeClassifier(min_samples_split=13, random_state=1)
model2.fit(train[Needed_columns], train["Lable"])
predictions = model2.predict(test[Needed_columns])
test_auc = roc_auc_score(test["Lable"], predictions)
train_predictions = model2.predict(train[Needed_columns])
train_auc = roc_auc_score(train["Lable"], train_predictions)
print(test_auc)
print(train_auc)

## Depth

In [ ]:
model2 = DecisionTreeClassifier(random_state=1)
model2 = DecisionTreeClassifier(min_samples_split=13,max_depth=5, random_state=1)
model2.fit(train[Needed_columns], train["Lable"])
predictions = model2.predict(test[Needed_columns])
test_auc = roc_auc_score(test["Lable"], predictions)
train_predictions = model2.predict(train[Needed_columns])
train_auc = roc_auc_score(train["Lable"], train_predictions)
print(test_auc)
print(train_auc)

## Depth 2
## Min Sample 90

In [ ]:
model2 = DecisionTreeClassifier(random_state=1)
model2 = DecisionTreeClassifier(min_samples_split=90,max_depth=2, random_state=1)
model2.fit(train[Needed_columns], train["Lable"])
predictions = model2.predict(test[Needed_columns])
test_auc = roc_auc_score(test["Lable"], predictions)
train_predictions = model2.predict(train[Needed_columns])
train_auc = roc_auc_score(train["Lable"], train_predictions)
print(test_auc)
print(train_auc)

## در بالا آندر فیت رخ داد

## داده ساختگی

In [ ]:
np.random.seed(2)
#.shape[0] یعنی تعداد رکورد دیتا ست
dataSet["noise"] = np.random.randint(4, size=dataSet.shape[0])

In [ ]:
Needed_columns = ["noise","age", "workclass", "education-num", "marital-status", "occupation", "relationship",
                  "race", "sex", "hours-per-week", "native-country"]
train_max_row = math.floor(dataSet.shape[0] * .8)
#floor: = or < 
train = dataSet.iloc[:train_max_row]
test = dataSet.iloc[train_max_row:]
model = DecisionTreeClassifier(random_state=1)
model.fit(train[Needed_columns], train["Lable"])
predictions = model.predict(test[Needed_columns])
Test_AUC = roc_auc_score(test["Lable"], predictions)
train_predictions = model.predict(train[Needed_columns])
train_auc = roc_auc_score(train["Lable"], train_predictions)
print(train_auc)
print(Test_AUC)