In [2]:
import pandas as pd
data = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/adults/adult.dat')
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Lable
0,25.0,Private,226802.0,11th,7.0,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38.0,Private,89814.0,HS-grad,9.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28.0,Local-gov,336951.0,Assoc-acdm,12.0,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44.0,Private,160323.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,34.0,Private,198693.0,10th,6.0,Never-married,Other-service,Not-in-family,White,Male,0.0,0.0,30.0,United-States,<=50K
5,63.0,Self-emp-not-inc,104626.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K
6,24.0,Private,369667.0,Some-college,10.0,Never-married,Other-service,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
7,55.0,Private,104996.0,7th-8th,4.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,10.0,United-States,<=50K
8,65.0,Private,184454.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K
9,36.0,Federal-gov,212465.0,Bachelors,13.0,Married-civ-spouse,Adm-clerical,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
10,26.0,Private,82091.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Female,0.0,0.0,39.0,United-States,<=50K
11,48.0,Private,279724.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K
12,43.0,Private,346189.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,50.0,United-States,>50K
13,20.0,State-gov,444554.0,Some-college,10.0,Never-married,Other-service,Own-child,White,Male,0.0,0.0,25.0,United-States,<=50K
14,43.0,Private,128354.0,HS-grad,9.0,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,30.0,United-States,<=50K
15,37.0,Private,60548.0,HS-grad,9.0,Widowed,Machine-op-inspct,Unmarried,White,Female,0.0,0.0,20.0,United-States,<=50K
16,34.0,Private,107914.0,Bachelors,13.0,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,47.0,United-States,>50K
17,34.0,Private,238588.0,Some-college,10.0,Never-married,Other-service,Own-child,Black,Female,0.0,0.0,35.0,United-States,<=50K
18,25.0,Private,220931.0,Bachelors,13.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,43.0,Peru,<=50K
19,25.0,Private,205947.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
20,45.0,Self-emp-not-inc,432824.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,7298.0,0.0,90.0,United-States,>50K
21,22.0,Private,236427.0,HS-grad,9.0,Never-married,Adm-clerical,Own-child,White,Male,0.0,0.0,20.0,United-States,<=50K
22,23.0,Private,134446.0,HS-grad,9.0,Separated,Machine-op-inspct,Unmarried,Black,Male,0.0,0.0,54.0,United-States,<=50K
23,54.0,Private,99516.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,35.0,United-States,<=50K
24,32.0,Self-emp-not-inc,109282.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,60.0,United-States,<=50K
25,46.0,State-gov,106444.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,7688.0,0.0,38.0,United-States,>50K
26,56.0,Self-emp-not-inc,186651.0,11th,7.0,Widowed,Other-service,Unmarried,White,Female,0.0,0.0,50.0,United-States,<=50K
27,24.0,Self-emp-not-inc,188274.0,Bachelors,13.0,Never-married,Sales,Not-in-family,White,Male,0.0,0.0,50.0,United-States,<=50K
28,23.0,Local-gov,258120.0,Some-college,10.0,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
29,26.0,Private,43311.0,HS-grad,9.0,Divorced,Exec-managerial,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45192,32.0,Private,211349.0,10th,6.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
45193,22.0,Private,203715.0,Some-college,10.0,Never-married,Adm-clerical,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
45194,31.0,Private,292592.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0.0,0.0,40.0,United-States,<=50K
45195,29.0,Private,125976.0,HS-grad,9.0,Separated,Sales,Unmarried,White,Female,0.0,0.0,35.0,United-States,<=50K
45196,34.0,Private,204461.0,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,>50K
45197,54.0,Private,337992.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0.0,0.0,50.0,Japan,>50K
45198,37.0,Private,179137.0,Some-college,10.0,Divorced,Adm-clerical,Unmarried,White,Female,0.0,0.0,39.0,United-States,<=50K
45199,22.0,Private,325033.0,12th,8.0,Never-married,Protective-serv,Own-child,Black,Male,0.0,0.0,35.0,United-States,<=50K
45200,34.0,Private,160216.0,Bachelors,13.0,Never-married,Exec-managerial,Not-in-family,White,Female,0.0,0.0,55.0,United-States,>50K
45201,30.0,Private,345898.0,HS-grad,9.0,Never-married,Craft-repair,Not-in-family,Black,Male,0.0,0.0,46.0,United-States,<=50K
45202,38.0,Private,139180.0,Bachelors,13.0,Divorced,Prof-specialty,Unmarried,Black,Female,15020.0,0.0,45.0,United-States,>50K
45203,45.0,State-gov,252208.0,HS-grad,9.0,Separated,Adm-clerical,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K
45204,45.0,Local-gov,119199.0,Assoc-acdm,12.0,Divorced,Prof-specialty,Unmarried,White,Female,0.0,0.0,48.0,United-States,<=50K
45205,31.0,Private,199655.0,Masters,14.0,Divorced,Other-service,Not-in-family,Other,Female,0.0,0.0,30.0,United-States,<=50K
45206,39.0,Local-gov,111499.0,Assoc-acdm,12.0,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,20.0,United-States,>50K
45207,37.0,Private,198216.0,Assoc-acdm,12.0,Divorced,Tech-support,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
45208,43.0,Private,260761.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,40.0,Mexico,<=50K
45209,65.0,Self-emp-not-inc,99359.0,Prof-school,15.0,Never-married,Prof-specialty,Not-in-family,White,Male,1086.0,0.0,60.0,United-States,<=50K
45210,43.0,State-gov,255835.0,Some-college,10.0,Divorced,Adm-clerical,Other-relative,White,Female,0.0,0.0,40.0,United-States,<=50K
45211,43.0,Self-emp-not-inc,27242.0,Some-college,10.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
45212,32.0,Private,34066.0,10th,6.0,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0.0,0.0,40.0,United-States,<=50K
45213,43.0,Private,84661.0,Assoc-voc,11.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,45.0,United-States,<=50K
45214,32.0,Private,116138.0,Masters,14.0,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,11.0,Taiwan,<=50K
45215,53.0,Private,321865.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
45216,22.0,Private,310152.0,Some-college,10.0,Never-married,Protective-serv,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
45217,27.0,Private,257302.0,Assoc-acdm,12.0,Married-civ-spouse,Tech-support,Wife,White,Female,0.0,0.0,38.0,United-States,<=50K
45218,40.0,Private,154374.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
45219,58.0,Private,151910.0,HS-grad,9.0,Widowed,Adm-clerical,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
45220,22.0,Private,201490.0,HS-grad,9.0,Never-married,Adm-clerical,Own-child,White,Male,0.0,0.0,20.0,United-States,<=50K
45221,52.0,Self-emp-inc,287927.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024.0,0.0,40.0,United-States,>50K

## Missing Values

In [3]:
train = data[0:1500]
test = data[1500:]
train_empty = train.isnull().sum()
print(train_empty)
df_not_Empty = train[train_empty[train_empty==0].index]

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
Lable             0
dtype: int64

## انتخاب فیچر کتگوریکال

In [4]:
print(train['race'].value_counts())

White                 1288
Black                  146
Asian-Pac-Islander      44
Amer-Indian-Eskimo      13
Other                    9
Name: race, dtype: int64

In [5]:
print(train['occupation'].value_counts())

Exec-managerial      223
Prof-specialty       208
Craft-repair         185
Adm-clerical         180
Sales                160
Other-service        146
Machine-op-inspct    115
Transport-moving      75
Handlers-cleaners     73
Tech-support          46
Farming-fishing       46
Protective-serv       31
Priv-house-serv       11
Armed-Forces           1
Name: occupation, dtype: int64

## String to Categorical

In [6]:
train['race'] = train['race'].astype('category')

C:\Users\ABA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [7]:
print(train['race'])

0                    Black
1                    White
2                    White
3                    Black
4                    White
5                    White
6                    White
7                    White
8                    White
9                    White
10                   White
11                   White
12                   White
13                   White
14                   White
15                   White
16                   White
17                   Black
18                   White
19                   White
20                   White
21                   White
22                   Black
23                   White
24                   White
25                   Black
26                   White
27                   White
28                   White
29                   White
               ...
1470                 White
1471                 White
1472                 White
1473                 White
1474                 White
1475                 White
1476                 White
1477                 White
1478                 White
1479                 White
1480                 White
1481                 Black
1482                 White
1483                 White
1484                 White
1485                 White
1486                 White
1487                 White
1488                 Black
1489    Asian-Pac-Islander
1490                 White
1491                 White
1492                 White
1493                 White
1494                 White
1495    Asian-Pac-Islander
1496                 White
1497                 White
1498                 White
1499                 Black
Name: race, Length: 1500, dtype: category
Categories (5, object): [Amer-Indian-Eskimo, Asian-Pac-Islander, Black, Other, White]

In [8]:
train['race'].cat.codes

0       2
1       4
2       4
3       2
4       4
5       4
6       4
7       4
8       4
9       4
10      4
11      4
12      4
13      4
14      4
15      4
16      4
17      2
18      4
19      4
20      4
21      4
22      2
23      4
24      4
25      2
26      4
27      4
28      4
29      4
       ..
1470    4
1471    4
1472    4
1473    4
1474    4
1475    4
1476    4
1477    4
1478    4
1479    4
1480    4
1481    2
1482    4
1483    4
1484    4
1485    4
1486    4
1487    4
1488    2
1489    1
1490    4
1491    4
1492    4
1493    4
1494    4
1495    1
1496    4
1497    4
1498    4
1499    2
Length: 1500, dtype: int8

In [10]:
train.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Lable
0,25.0,Private,226802.0,11th,7.0,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38.0,Private,89814.0,HS-grad,9.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28.0,Local-gov,336951.0,Assoc-acdm,12.0,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44.0,Private,160323.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,34.0,Private,198693.0,10th,6.0,Never-married,Other-service,Not-in-family,White,Male,0.0,0.0,30.0,United-States,<=50K

In [8]:
categoricals = df_not_Empty.select_dtypes(include=['object']).columns
for col in categoricals:
    print(col+":", len(train[col].unique()))

workclass: 6
education: 16
marital-status: 7
occupation: 14
relationship: 6
race: 5
sex: 2
native-country: 31
Lable: 2

In [9]:
for col in categoricals:
    train[col] = train[col].astype('category')

C:\Users\ABA\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

## ِDummy Vars

In [10]:
dummy_cols = pd.DataFrame()

for col in categoricals:
    col_dummies = pd.get_dummies(train[col])
    train = pd.concat([train, col_dummies], axis=1)
    del train[col]
train

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,Federal-gov,Local-gov,Private,Self-emp-inc,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,United-States,Vietnam,<=50K,>50K
0,25.0,226802.0,7.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,38.0,89814.0,9.0,0.0,0.0,50.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
2,28.0,336951.0,12.0,0.0,0.0,40.0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,44.0,160323.0,10.0,7688.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4,34.0,198693.0,6.0,0.0,0.0,30.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5,63.0,104626.0,15.0,3103.0,0.0,32.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
6,24.0,369667.0,10.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
7,55.0,104996.0,4.0,0.0,0.0,10.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
8,65.0,184454.0,9.0,6418.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
9,36.0,212465.0,13.0,0.0,0.0,40.0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
10,26.0,82091.0,9.0,0.0,0.0,39.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
11,48.0,279724.0,9.0,3103.0,0.0,48.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
12,43.0,346189.0,14.0,0.0,0.0,50.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
13,20.0,444554.0,10.0,0.0,0.0,25.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
14,43.0,128354.0,9.0,0.0,0.0,30.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
15,37.0,60548.0,9.0,0.0,0.0,20.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
16,34.0,107914.0,13.0,0.0,0.0,47.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
17,34.0,238588.0,10.0,0.0,0.0,35.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
18,25.0,220931.0,13.0,0.0,0.0,43.0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
19,25.0,205947.0,13.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
20,45.0,432824.0,9.0,7298.0,0.0,90.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
21,22.0,236427.0,9.0,0.0,0.0,20.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
22,23.0,134446.0,9.0,0.0,0.0,54.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
23,54.0,99516.0,9.0,0.0,0.0,35.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
24,32.0,109282.0,10.0,0.0,0.0,60.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
25,46.0,106444.0,10.0,7688.0,0.0,38.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
26,56.0,186651.0,7.0,0.0,0.0,50.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
27,24.0,188274.0,13.0,0.0,0.0,50.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
28,23.0,258120.0,10.0,0.0,0.0,40.0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
29,26.0,43311.0,9.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,23.0,200593.0,13.0,0.0,0.0,40.0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
1471,20.0,311376.0,10.0,0.0,0.0,25.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1472,58.0,206814.0,13.0,7688.0,0.0,50.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1473,21.0,278391.0,9.0,0.0,0.0,25.0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1474,32.0,364657.0,13.0,0.0,0.0,50.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1475,62.0,175080.0,9.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1476,43.0,161240.0,11.0,0.0,0.0,60.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1477,20.0,162282.0,10.0,0.0,0.0,60.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1478,23.0,199419.0,10.0,0.0,0.0,20.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1479,26.0,171114.0,13.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1480,33.0,208855.0,15.0,0.0,0.0,60.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1481,30.0,381030.0,10.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1482,63.0,219337.0,4.0,3471.0,0.0,45.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1483,45.0,180010.0,9.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1484,39.0,189382.0,10.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1485,26.0,121712.0,9.0,0.0,0.0,30.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1486,39.0,352188.0,13.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1487,34.0,398874.0,13.0,0.0,0.0,42.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1488,33.0,191930.0,9.0,0.0,0.0,50.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1489,26.0,269168.0,10.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1490,40.0,173651.0,10.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1491,49.0,149337.0,9.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1492,65.0,173483.0,13.0,0.0,0.0,35.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1493,19.0,223669.0,7.0,0.0,0.0,20.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1494,47.0,182177.0,10.0,0.0,0.0,23.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1495,24.0,109414.0,10.0,0.0,0.0,20.0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1496,55.0,150917.0,10.0,0.0,1977.0,45.0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
1497,61.0,39128.0,9.0,0.0,0.0,35.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1498,47.0,103540.0,13.0,0.0,0.0,50.0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
1499,64.0,110212.0,9.0,0.0,0.0,40.0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

## یافت و مدیریت مقادیر از دست رفته

In [11]:
train_novalue = train.isnull().sum()
df_missings = train[train_novalue[(train_novalue>0) & (train_novalue<584)].index]
print(df_missings.isnull().sum())
print(df_missings.dtypes)

Series([], dtype: float64)
Series([], dtype: object)

In [12]:
#مقادیر خالی وجود ندارد. دیتا ست دیگری را باز میکنیم.

In [13]:
data = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/LinearRegressor/Housing_Data.txt', delimiter="\t")
data_null = data.isnull().sum()
data_missing = data[data_null[(data_null>0) & (data_null<584)].index]
print(data_missing.isnull().sum())
print(data_missing.dtypes)

Lot Frontage      490
Mas Vnr Type       23
Mas Vnr Area       23
Bsmt Qual          80
Bsmt Cond          80
Bsmt Exposure      83
BsmtFin Type 1     80
BsmtFin SF 1        1
BsmtFin Type 2     81
BsmtFin SF 2        1
Bsmt Unf SF         1
Total Bsmt SF       1
Electrical          1
Bsmt Full Bath      2
Bsmt Half Bath      2
Garage Type       157
Garage Yr Blt     159
Garage Finish     159
Garage Cars         1
Garage Area         1
Garage Qual       159
Garage Cond       159
dtype: int64
Lot Frontage      float64
Mas Vnr Type       object
Mas Vnr Area      float64
Bsmt Qual          object
Bsmt Cond          object
Bsmt Exposure      object
BsmtFin Type 1     object
BsmtFin SF 1      float64
BsmtFin Type 2     object
BsmtFin SF 2      float64
Bsmt Unf SF       float64
Total Bsmt SF     float64
Electrical         object
Bsmt Full Bath    float64
Bsmt Half Bath    float64
Garage Type        object
Garage Yr Blt     float64
Garage Finish      object
Garage Cars       float64
Garage Area       float64
Garage Qual        object
Garage Cond        object
dtype: object

## پرکردن مقادیر خالی

In [15]:
float_column = data_missing.select_dtypes(include=['float'])
float_column = float_column.fillna(float_column.mean())
print(float_column.isnull().sum())

Lot Frontage      0
Mas Vnr Area      0
BsmtFin SF 1      0
BsmtFin SF 2      0
Bsmt Unf SF       0
Total Bsmt SF     0
Bsmt Full Bath    0
Bsmt Half Bath    0
Garage Yr Blt     0
Garage Cars       0
Garage Area       0
dtype: int64