In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/baltimore-city-employee-salaries-fy2019-1.csv')
data

,NAME,JOBTITLE,DEPTID,DESCR,HIRE_DT,ANNUAL_RT,Gross
0,"Aaron,Kareem D",Utilities Inst Repair I,A50550,DPW-Water & Waste Water (550),08/27/2018 12:00:00 AM,32470.0,25743.94
1,"Aaron,Patricia G",Facilities/Office Services II,A03031,OED-Employment Dev (031),10/24/1979 12:00:00 AM,60200.0,57806.13
2,"Abadir,Adam O",Council Technician,A02002,City Council (002),12/12/2016 12:00:00 AM,64823.0,64774.11
3,"Abaku,Aigbolosimuan O",Police Officer,A99094,Police Department (094),04/17/2018 12:00:00 AM,53640.0,59361.55
4,"Abbeduto,Mack",Assistant State's Attorney,A29011,States Attorneys Office (011),05/22/2017 12:00:00 AM,68562.0,61693.59
5,"Abbott,Ethan N",Recreation Arts Instructor,A68002,R&P-Parks (002),04/11/2018 12:00:00 AM,33280.0,26156.48
6,"Abbott-Cole,Michelle",Operations Officer III,A90005,TRANS-Traffic (005),11/28/2014 12:00:00 AM,75110.0,75529.99
7,"Abdal-Rahim,Naim A",Fire Pump Operator Suppression,A64120,Fire Department (120),03/30/2011 12:00:00 AM,69595.0,82132.61
8,"Abdi,Ezekiel W",Police Sergeant,A99160,Police Department (160),06/14/2007 12:00:00 AM,93284.0,122992.10
9,"Abdul Adl,Attrice A",Radio Dispatcher Sheriff,A38410,Sheriff's Office (410),09/02/1999 12:00:00 AM,50079.0,58459.78
10,"Abdul Aziz,Hajr E",Swimming Pool Operator,P04002,R&P-Recreation (part-time) (,06/01/2017 12:00:00 AM,28554.0,15807.64
11,"Abdul Aziz,Yaqub M",Swimming Pool Operator,P04002,R&P-Recreation (part-time) (,06/01/2017 12:00:00 AM,28554.0,6417.90
12,"Abdul Saboor,Dana N",Paralegal,A99393,Police Department (393),04/13/1998 12:00:00 AM,57857.0,35715.20
13,"Abdul,Jalil",Engineer I,A50101,DPW-Water & Waste Water (101),07/17/2017 12:00:00 AM,64505.0,65577.50
14,"Abdul-Jabbar,Bushra A",Social Service Coordinator,A65028,HLTH-Health Department (028),04/14/2008 12:00:00 AM,46395.0,46359.55
15,"Abdul-Khaliq,Amahl",Recreation Leader II,A04005,R&P-Recreation (005),06/06/2019 12:00:00 AM,32131.0,NaN
16,"Abdullah,Beverly A",Office Support Specialist III,A06004,Housing & Community Dev (004),12/01/1986 12:00:00 AM,41757.0,44522.96
17,"Abdullahi,Sharon M",911 Operator,A64604,Fire Department (604),06/10/2004 12:00:00 AM,56322.0,53751.88
18,"Abdullateef,Muhammed L",Supt of Public Bldg Repair,A85001,General Services (001),05/09/2019 12:00:00 AM,78000.0,9000.00
19,"Abdulrahman,Mustafa H",Police Officer Trainee,A99416,Police Department (416),12/28/2018 12:00:00 AM,53512.0,25347.99
20,"Abdul-Saboor,Jamillah",Printer Library,A75055,Enoch Pratt Free Library (055),07/27/2009 12:00:00 AM,44584.0,42555.83
21,"Abdunafi,Karim",Community Aide,A04015,R&P-Recreation (015),06/13/2019 12:00:00 AM,24960.0,NaN
22,"Abdur-Rahman,Diane",Facilities/Office Services I,A03092,OED-Employment Dev (092),03/27/2017 12:00:00 AM,25363.0,25649.94
23,"Abdurrahman,Saleh Z",Lifeguard I,P04002,R&P-Recreation (part-time) (,06/04/2019 12:00:00 AM,23920.0,1.00
24,"Abebe,Miraf E",Auditor II,A24002,COMP-Audits (002),02/06/2012 12:00:00 AM,67236.0,60600.92
25,"Abend-Kollin,Emily L",Fleet Quality Control Analyst,A85301,General Services (301),01/05/2017 12:00:00 AM,47828.0,49133.11
26,"Abid,Amal",Engineer II,A49102,TRANS-Highways (102),12/02/2013 12:00:00 AM,71774.0,71630.83
27,"Abid,Paula",Recreation Arts Instructor,A04009,R&P-Recreation (009),06/25/2007 12:00:00 AM,24960.0,3591.96
28,"Abraham,Donta D",Laborer Hourly,B70357,DPW-Solid Waste (wkly) (357),10/16/2000 12:00:00 AM,34247.0,52336.71
29,"Abraham,Santhosh",Accountant II,A50100,DPW-Water & Waste Water (100),12/31/2007 12:00:00 AM,60700.0,61478.56
...,...,...,...,...,...,...,...
13781,"Zelno,Patrick",Police Officer,A99033,Police Department (033),03/31/2014 12:00:00 AM,72254.0,112100.94
13782,"Zenker,Matthew J",Police Officer EID,A99MIL,Police Department (MIL),12/02/2011 12:00:00 AM,77635.0,1000.00
13783,"Zeno Jr.,Anthony J",Police Officer EID,A99348,Police Department (348),07/01/2014 12:00:00 AM,73999.0,82674.46
13784,"Zepp,David T",Fire Lt EMS EMT-P,A64466,Fire Department (466),01/17/2001 12:00:00 AM,84177.0,92280.05
13785,"Zerance,Michael A",Recreation Leader II,A04002,R&P-Recreation (002),06/07/2011 12:00:00 AM,32131.0,26076.26
13786,"Zero,Benjamin E",Police Officer EID,A99124,Police Department (124),03/02/2011 12:00:00 AM,78394.0,83918.44
13787,"Zhai,Shuang",Design Planner II,A67002,R&P-Administration (002),07/15/2019 12:00:00 AM,74000.0,NaN
13788,"Zhang,Qiannan",Retirement Benefit Anal I,A52003,ERS/EOS Admin (003),06/18/2018 12:00:00 AM,45659.0,45622.63
13789,"Zhang,Xiaojing",Accounting Manager,A50100,DPW-Water & Waste Water (100),09/03/2013 12:00:00 AM,82170.0,81416.22
13790,"Zhang,Zhiang J",Police Officer Trainee,A99416,Police Department (416),12/10/2018 12:00:00 AM,53512.0,30889.79
13791,"Zhu,Yue",Lib Wide Area Network Admin,A75086,Enoch Pratt Free Library (086),09/10/2018 12:00:00 AM,89058.0,68505.70
13792,"Ziegler,Francis A",Public Works Inspector III,A50803,DPW-Water & Waste Water (803),01/16/1996 12:00:00 AM,68751.0,81025.74
13793,"Zielinski,John R",Instrumentation Technician II,A50209,DPW-Water & Waste Water (209),04/19/1999 12:00:00 AM,57916.0,74302.46
13794,"Ziemski,Benedict J",Engineer Supervisor,A50209,DPW-Water & Waste Water (209),04/07/1983 12:00:00 AM,93738.0,95663.05
13795,"Zillmann-Georgie,Josephine",Deputy Sheriff,A38001,Sheriff's Office (001),05/01/2008 12:00:00 AM,60377.0,65863.52
13796,"Zimmerman Jr,Jason A",Police Officer,A99064,Police Department (064),02/19/2014 12:00:00 AM,64431.0,63209.23
13797,"Zimmerman,Donovan D",Maintenance Mechanic,A91014,M-R Convention Center (014),05/16/2016 12:00:00 AM,46512.0,44862.13
13798,"Zimmerman,Jeremy E",Police Officer,A99395,Police Department (395),04/15/2013 12:00:00 AM,72977.0,94903.97
13799,"Zimmerman,Shelley B",Council Technician,A02002,City Council (002),12/07/2016 12:00:00 AM,65897.0,66607.66
13800,"Zimrin,Evan R",Police Officer EID,A99335,Police Department (335),03/12/2013 12:00:00 AM,74737.0,117151.28
13801,"Zinn,Rachel C",Budget Management Analyst II,A23001,FIN-Admin & Budgets (001),09/23/2017 12:00:00 AM,91800.0,92436.96
13802,"Zopp,Rickie G",EMT Firefighter Suppression,A64133,Fire Department (133),03/08/2017 12:00:00 AM,49887.0,54056.78
13803,"Zoppo Jr,Phillip A",Mason Supervisor,A50509,DPW-Water & Waste Water (509),04/04/1988 12:00:00 AM,58568.0,70192.18
13804,"Zoppo,Catherine B",Real Estate Agent I,A15001,COMP-Real Estate (001),03/14/1977 12:00:00 AM,64860.0,65310.00
13805,"Zorbach,Michael K",Police Officer,A99224,Police Department (224),05/02/2012 12:00:00 AM,72977.0,73012.57
13806,"Zou,Zhi Fan",Police Officer Trainee,A99163,Police Department (163),04/11/2018 12:00:00 AM,53512.0,39631.51
13807,"Zovistoski,Zachary D",Police Officer,A99006,Police Department (006),12/17/2013 12:00:00 AM,72254.0,76767.33
13808,"Zuhoski,Timothy C",Police Officer EID,A99196,Police Department (196),01/31/2017 12:00:00 AM,55526.0,65534.27
13809,"Zuniga,Linette",Community Outreach Worker,A65527,HLTH-Health Department (527),10/20/2016 12:00:00 AM,30279.0,26655.90
13810,"Zyla,David C",Emergency Medical Technician,A64462,Fire Department (462),09/19/2018 12:00:00 AM,34298.0,26145.80

In [3]:
data.index.name = None
dataType = type(data)
dataShape = data.shape
dataType

pandas.core.frame.DataFrame

In [4]:
dataShape

(13811, 7)

In [5]:
data.head(6)

,NAME,JOBTITLE,DEPTID,DESCR,HIRE_DT,ANNUAL_RT,Gross
0,"Aaron,Kareem D",Utilities Inst Repair I,A50550,DPW-Water & Waste Water (550),08/27/2018 12:00:00 AM,32470.0,25743.94
1,"Aaron,Patricia G",Facilities/Office Services II,A03031,OED-Employment Dev (031),10/24/1979 12:00:00 AM,60200.0,57806.13
2,"Abadir,Adam O",Council Technician,A02002,City Council (002),12/12/2016 12:00:00 AM,64823.0,64774.11
3,"Abaku,Aigbolosimuan O",Police Officer,A99094,Police Department (094),04/17/2018 12:00:00 AM,53640.0,59361.55
4,"Abbeduto,Mack",Assistant State's Attorney,A29011,States Attorneys Office (011),05/22/2017 12:00:00 AM,68562.0,61693.59
5,"Abbott,Ethan N",Recreation Arts Instructor,A68002,R&P-Parks (002),04/11/2018 12:00:00 AM,33280.0,26156.48

In [6]:
data.tail(8)

,NAME,JOBTITLE,DEPTID,DESCR,HIRE_DT,ANNUAL_RT,Gross
13803,"Zoppo Jr,Phillip A",Mason Supervisor,A50509,DPW-Water & Waste Water (509),04/04/1988 12:00:00 AM,58568.0,70192.18
13804,"Zoppo,Catherine B",Real Estate Agent I,A15001,COMP-Real Estate (001),03/14/1977 12:00:00 AM,64860.0,65310.00
13805,"Zorbach,Michael K",Police Officer,A99224,Police Department (224),05/02/2012 12:00:00 AM,72977.0,73012.57
13806,"Zou,Zhi Fan",Police Officer Trainee,A99163,Police Department (163),04/11/2018 12:00:00 AM,53512.0,39631.51
13807,"Zovistoski,Zachary D",Police Officer,A99006,Police Department (006),12/17/2013 12:00:00 AM,72254.0,76767.33
13808,"Zuhoski,Timothy C",Police Officer EID,A99196,Police Department (196),01/31/2017 12:00:00 AM,55526.0,65534.27
13809,"Zuniga,Linette",Community Outreach Worker,A65527,HLTH-Health Department (527),10/20/2016 12:00:00 AM,30279.0,26655.90
13810,"Zyla,David C",Emergency Medical Technician,A64462,Fire Department (462),09/19/2018 12:00:00 AM,34298.0,26145.80

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13811 entries, 0 to 13810
Data columns (total 7 columns):
NAME         13811 non-null object
JOBTITLE     13811 non-null object
DEPTID       13811 non-null object
DESCR        13811 non-null object
HIRE_DT      13807 non-null object
ANNUAL_RT    13811 non-null float64
Gross        13158 non-null float64
dtypes: float64(2), object(5)
memory usage: 755.4+ KB

### df.loc[row_label, column_label]

In [8]:
JOBTITLE = data["JOBTITLE"]
aa = type(JOBTITLE)
aa

pandas.core.series.Series

In [9]:
data.loc[1, 'JOBTITLE']

'Facilities/Office Services II'

In [10]:
data.loc[:, 'JOBTITLE']

0               Utilities Inst Repair I
1         Facilities/Office Services II
2                    Council Technician
3                        Police Officer
4            Assistant State's Attorney
5            Recreation Arts Instructor
6                Operations Officer III
7        Fire Pump Operator Suppression
8                       Police Sergeant
9              Radio Dispatcher Sheriff
10               Swimming Pool Operator
11               Swimming Pool Operator
12                            Paralegal
13                           Engineer I
14           Social Service Coordinator
15                 Recreation Leader II
16        Office Support Specialist III
17                         911 Operator
18           Supt of Public Bldg Repair
19               Police Officer Trainee
20                      Printer Library
21                       Community Aide
22         Facilities/Office Services I
23                          Lifeguard I
24                           Auditor II
25        Fleet Quality Control Analyst
26                          Engineer II
27           Recreation Arts Instructor
28                       Laborer Hourly
29                        Accountant II
                      ...
13781                    Police Officer
13782                Police Officer EID
13783                Police Officer EID
13784                 Fire Lt EMS EMT-P
13785              Recreation Leader II
13786                Police Officer EID
13787                 Design Planner II
13788         Retirement Benefit Anal I
13789                Accounting Manager
13790            Police Officer Trainee
13791       Lib Wide Area Network Admin
13792        Public Works Inspector III
13793     Instrumentation Technician II
13794               Engineer Supervisor
13795                    Deputy Sheriff
13796                    Police Officer
13797              Maintenance Mechanic
13798                    Police Officer
13799                Council Technician
13800                Police Officer EID
13801      Budget Management Analyst II
13802       EMT Firefighter Suppression
13803                  Mason Supervisor
13804               Real Estate Agent I
13805                    Police Officer
13806            Police Officer Trainee
13807                    Police Officer
13808                Police Officer EID
13809         Community Outreach Worker
13810      Emergency Medical Technician
Name: JOBTITLE, Length: 13811, dtype: object

In [11]:
data.loc[:, 'JOBTITLE'].unique()

array(['Utilities Inst Repair I', 'Facilities/Office Services II',
       'Council Technician', ..., 'Bike Share Program Coordinator',
       'Tree Service Supv I', 'Lib Wide Area Network Admin'], dtype=object)

In [12]:
data.loc[:,['JOBTITLE','Gross']]

                             JOBTITLE      Gross
0             Utilities Inst Repair I   25743.94
1       Facilities/Office Services II   57806.13
2                  Council Technician   64774.11
3                      Police Officer   59361.55
4          Assistant State's Attorney   61693.59
5          Recreation Arts Instructor   26156.48
6              Operations Officer III   75529.99
7      Fire Pump Operator Suppression   82132.61
8                     Police Sergeant  122992.10
9            Radio Dispatcher Sheriff   58459.78
10             Swimming Pool Operator   15807.64
11             Swimming Pool Operator    6417.90
12                          Paralegal   35715.20
13                         Engineer I   65577.50
14         Social Service Coordinator   46359.55
15               Recreation Leader II        NaN
16      Office Support Specialist III   44522.96
17                       911 Operator   53751.88
18         Supt of Public Bldg Repair    9000.00
19             Police Officer Trainee   25347.99
20                    Printer Library   42555.83
21                     Community Aide        NaN
22       Facilities/Office Services I   25649.94
23                        Lifeguard I       1.00
24                         Auditor II   60600.92
25      Fleet Quality Control Analyst   49133.11
26                        Engineer II   71630.83
27         Recreation Arts Instructor    3591.96
28                     Laborer Hourly   52336.71
29                      Accountant II   61478.56
...                               ...        ...
13781                  Police Officer  112100.94
13782              Police Officer EID    1000.00
13783              Police Officer EID   82674.46
13784               Fire Lt EMS EMT-P   92280.05
13785            Recreation Leader II   26076.26
13786              Police Officer EID   83918.44
13787               Design Planner II        NaN
13788       Retirement Benefit Anal I   45622.63
13789              Accounting Manager   81416.22
13790          Police Officer Trainee   30889.79
13791     Lib Wide Area Network Admin   68505.70
13792      Public Works Inspector III   81025.74
13793   Instrumentation Technician II   74302.46
13794             Engineer Supervisor   95663.05
13795                  Deputy Sheriff   65863.52
13796                  Police Officer   63209.23
13797            Maintenance Mechanic   44862.13
13798                  Police Officer   94903.97
13799              Council Technician   66607.66
13800              Police Officer EID  117151.28
13801    Budget Management Analyst II   92436.96
13802     EMT Firefighter Suppression   54056.78
13803                Mason Supervisor   70192.18
13804             Real Estate Agent I   65310.00
13805                  Police Officer   73012.57
13806          Police Officer Trainee   39631.51
13807                  Police Officer   76767.33
13808              Police Officer EID   65534.27
13809       Community Outreach Worker   26655.90
13810    Emergency Medical Technician   26145.80

[13811 rows x 2 columns]

In [13]:
data.loc[5:10,['JOBTITLE','Gross']]

                          JOBTITLE      Gross
5       Recreation Arts Instructor   26156.48
6           Operations Officer III   75529.99
7   Fire Pump Operator Suppression   82132.61
8                  Police Sergeant  122992.10
9         Radio Dispatcher Sheriff   58459.78
10          Swimming Pool Operator   15807.64

## Select & Single Record

In [12]:
SelectData = data.loc[1:10,['JOBTITLE','Gross']]
single_record = SelectData.loc[:]
print(type(single_record))
print(single_record)

<class 'pandas.core.frame.DataFrame'>
                          JOBTITLE      Gross
1    Facilities/Office Services II   57806.13
2               Council Technician   64774.11
3                   Police Officer   59361.55
4       Assistant State's Attorney   61693.59
5       Recreation Arts Instructor   26156.48
6           Operations Officer III   75529.99
7   Fire Pump Operator Suppression   82132.61
8                  Police Sergeant  122992.10
9         Radio Dispatcher Sheriff   58459.78
10          Swimming Pool Operator   15807.64

In [15]:
some_records =SelectData[5:10]
some_records

                          JOBTITLE      Gross
6           Operations Officer III   75529.99
7   Fire Pump Operator Suppression   82132.61
8                  Police Sergeant  122992.10
9         Radio Dispatcher Sheriff   58459.78
10          Swimming Pool Operator   15807.64

## df['column']  / df.loc[rows,columns]

In [16]:
some_records2 =data.loc[5:10,"Gross"]
some_records2

5      26156.48
6      75529.99
7      82132.61
8     122992.10
9      58459.78
10     15807.64
Name: Gross, dtype: float64

### Series.value_counts()
### مقادیر یکتا و تعداد آنها در سری

In [13]:
data['JOBTITLE'].value_counts()

Police Officer                    1474
Laborer Hourly                     548
Community Aide                     414
EMT Firefighter Suppression        378
Police Officer EID                 275
Office Support Specialist III      271
Crossing Guard                     249
Police Sergeant                    237
Recreation Arts Instructor         195
Police Officer Trainee             192
Assistant State's Attorney         147
Solid Waste Worker                 143
Motor Vehicle Driver I Hourly      135
Firefighter Paramedic Supp         135
Contract Srvc Specialist II        135
Fire Lt Suppression                125
School Health Aide 10 Mth          116
Seasonal Maint Aide                115
Fire Emergency Veh Drvr Supp       113
Office Support Specialist II       111
Police Sergeant EID                105
Fire Pump Operator Suppression      95
Recreation Activities Asst          93
Transportation Enforc Off I         91
Recreation Leader II                90
Paramedic EMT-P                     89
School Health Aide                  85
Automotive Mechanic                 85
Contract Srvc Specialist I          84
Deputy Sheriff                      84
                                  ...
Superintendent Parking Enfor         1
Vice President City Council          1
Legal Stenographer SAO               1
Traffic Investigator III             1
Epidemiologist Supervisor            1
Public Information Officer           1
Cashier Supervisor I                 1
Inspection Associate II              1
E-Discovery Coordinator              1
Criminal Justice Associate           1
Real Estate Agent Supervisor         1
BPD 1                                1
Account Executive Supervisor         1
Property Transfer Supervisor         1
City Solicitor                       1
Naturalist                           1
Aviation Maintenance Prog Supv       1
Senior Sales Manager                 1
Safety Enforcement Officer III       1
Asst Chief Div of Utilities          1
Legal Assistant Supervisor           1
Superintendent Conduits              1
Food Policy Director                 1
Insurance Risk Analyst               1
Liquor Brd Chief Inspector           1
Towing Services Rep II               1
Network Operations Coord Lib         1
Const Bldg Inspector II DGS          1
Communications Analyst I             1
Training Coordinator                 1
Name: JOBTITLE, Length: 1010, dtype: int64

## Deputy Sheriff تعداد شغل با نام

In [14]:
jobSeries = data['JOBTITLE'].value_counts()
jobSeries.loc['Deputy Sheriff']

84

# حل تمرین

In [18]:
mydf = data.loc[100:200,['JOBTITLE','Gross','DEPTID']]
vari = mydf.loc[120:190,'DEPTID'].value_counts()
vari.max()

3