In [2]:
import pandas as pd

In [3]:
MainDF = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/revenue-budget-financial-plan.csv')
MainDF.head()

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 1 Revenue Amount,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
0,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00001,REAL PROP TAX 1ST QUART,REAL PROP TAX 1ST QUART,10386162000,10386162000,2017,10364353000,10959257000,11607958000,12151245000
1,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00002,REAL PROP TAX 2ND QUART,REAL PROP TAX 2ND QUART,1823062000,1823062000,2017,1823017000,1927657000,2041759000,2137319000
2,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00003,REAL PROP TAX 3RD QUART,REAL ESTATE TAXES 3RD QUARTER,10167635000,10167635000,2017,9991423000,10564922000,11190281000,11714020000
3,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00004,REAL PROP TAX 4TH QUART,REAL PROP TAX 4TH QUART,1668138000,1668138000,2017,1866204000,1973323000,2090128000,2187952000
4,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00021,REAL ESTATE TAX REFUNDS,GEN PROPERTY TAXES REFUNDS,-400000000,-400000000,2017,-400000000,-400000000,-400000000,-400000000

In [5]:
pd.read_csv?

In [12]:
MainDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3213 entries, 0 to 3212
Data columns (total 22 columns):
Publication Date                  3213 non-null object
Fiscal Year                       3213 non-null int64
Fundind Source Name               3213 non-null object
FPS Group                         3213 non-null int64
FPS Group Name                    3213 non-null object
Agency Number                     3213 non-null float64
Agency Name                       3213 non-null object
Revenue Category                  3213 non-null int64
Revenue Category Name             3213 non-null object
Revenue Class Code                3213 non-null float64
Revenue Class Name                3213 non-null object
Budget Code                       3213 non-null object
Revenue Source                    3213 non-null object
Revenue Source Name               3213 non-null object
Revenue Structure Description     3213 non-null object
Adopted Budget Amount             3213 non-null int64
Current Modified Budget Amount    3213 non-null int64
Yr1_FY                            3213 non-null int64
Year 1 Revenue Amount             3213 non-null int64
Year 2 Revenue Amount             3213 non-null int64
Year 3 Revenue Amount             3213 non-null int64
Year 4 Revenue Amount             3213 non-null int64
dtypes: float64(2), int64(10), object(10)
memory usage: 552.3+ KB

In [14]:
MainDF.loc[1:3]

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 1 Revenue Amount,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
1,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00002,REAL PROP TAX 2ND QUART,REAL PROP TAX 2ND QUART,1823062000,1823062000,2017,1823017000,1927657000,2041759000,2137319000
2,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00003,REAL PROP TAX 3RD QUART,REAL ESTATE TAXES 3RD QUARTER,10167635000,10167635000,2017,9991423000,10564922000,11190281000,11714020000
3,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,00004,REAL PROP TAX 4TH QUART,REAL PROP TAX 4TH QUART,1668138000,1668138000,2017,1866204000,1973323000,2090128000,2187952000

In [3]:
MainDF1 = pd.read_csv('C:/Users/ABA/Desktop/nikamooz/mainCourseSTuuf/dataset/revenue-budget-financial-plan.csv'
                      , index_col= 'Year 1 Revenue Amount')
MainDF1.head()

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Budget Code,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
Year 1 Revenue Amount,,,,,,,,,,,,,,,,,,,,,
10364353000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00001,REAL PROP TAX 1ST QUART,REAL PROP TAX 1ST QUART,10386162000,10386162000,2017,10959257000,11607958000,12151245000
1823017000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00002,REAL PROP TAX 2ND QUART,REAL PROP TAX 2ND QUART,1823062000,1823062000,2017,1927657000,2041759000,2137319000
9991423000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00003,REAL PROP TAX 3RD QUART,REAL ESTATE TAXES 3RD QUARTER,10167635000,10167635000,2017,10564922000,11190281000,11714020000
1866204000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00004,REAL PROP TAX 4TH QUART,REAL PROP TAX 4TH QUART,1668138000,1668138000,2017,1973323000,2090128000,2187952000
-400000000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00021,REAL ESTATE TAX REFUNDS,GEN PROPERTY TAXES REFUNDS,-400000000,-400000000,2017,-400000000,-400000000,-400000000

In [4]:
MainDF1.index.name = None
MainDF1.head()

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Budget Code,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
10364353000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00001,REAL PROP TAX 1ST QUART,REAL PROP TAX 1ST QUART,10386162000,10386162000,2017,10959257000,11607958000,12151245000
1823017000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00002,REAL PROP TAX 2ND QUART,REAL PROP TAX 2ND QUART,1823062000,1823062000,2017,1927657000,2041759000,2137319000
9991423000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00003,REAL PROP TAX 3RD QUART,REAL ESTATE TAXES 3RD QUARTER,10167635000,10167635000,2017,10564922000,11190281000,11714020000
1866204000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00004,REAL PROP TAX 4TH QUART,REAL PROP TAX 4TH QUART,1668138000,1668138000,2017,1973323000,2090128000,2187952000
-400000000,2016 11 17,2017,City Funds,1,Real Property,2.0,Mayoralty,20,TAXES,1.0,...,0421,00021,REAL ESTATE TAX REFUNDS,GEN PROPERTY TAXES REFUNDS,-400000000,-400000000,2017,-400000000,-400000000,-400000000

In [5]:
sixth_record = MainDF.iloc[5]
sixth_record

Publication Date                                    2016 11 17
Fiscal Year                                               2017
Fundind Source Name                                 City Funds
FPS Group                                                    1
FPS Group Name                                   Real Property
Agency Number                                                2
Agency Name                                          Mayoralty
Revenue Category                                            20
Revenue Category Name                                    TAXES
Revenue Class Code                                           1
Revenue Class Name                      GENERAL PROPERTY TAXES
Budget Code                                               0421
Revenue Source                                           00034
Revenue Source Name               REAL PROPERTY TAX LIEN SALES
Revenue Structure Description     REAL PROPERTY TAX LIEN SALES
Adopted Budget Amount                                 80000000
Current Modified Budget Amount                        80000000
Yr1_FY                                                    2017
Year 1 Revenue Amount                                 80000000
Year 2 Revenue Amount                                 80000000
Year 3 Revenue Amount                                 80000000
Year 4 Revenue Amount                                 80000000
Name: 5, dtype: object

In [6]:
sixthRowColumn = MainDF.iloc[5,5]
sixthRowColumn

2.0

In [7]:
isNull = MainDF["Revenue Source"].isnull()
isNotNull = MainDF["Revenue Category"].notnull()
print(isNull.head(),isNotNull.head())

0    False
1    False
2    False
3    False
4    False
Name: Revenue Source, dtype: bool 0    True
1    True
2    True
3    True
4    True
Name: Revenue Category, dtype: bool

##   ØªÙ…Ø±ÛŒÙ†: Ø³ÙˆØ¯ Ø³Ø§Ù„Ù‡Ø§ÛŒ Ø§ÙˆÙ„ Ùˆ Ø¯ÙˆÙ… Ùˆ Ø³ÙˆÙ…  Ø¢Ù†Ù‡Ø§ÛŒÛŒ Ú©Ù‡ Ú©ØªÚ¯ÙˆØ±ÛŒ Ø³ÙˆØ¯ Ø³Ø§Ù„Ø§Ù†Ù‡ Ø¢Ù†Ù‡Ø§ 20 Ø§Ø³Øª

In [8]:
null_previous_rank = df[df["previous_rank"].isnull()][["....","....", "....."]]

NameError: name 'df' is not defined

In [9]:
bigRev = MainDF["Year 1 Revenue Amount"] > 10000000
smallRev = MainDF["Year 2 Revenue Amount"] < 1222200
combined = bigRev & smallRev
MainDF[combined].head(5)

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 1 Revenue Amount,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
274,2016 11 17,2017,City Funds,23,Miscellaneous,2.0,Mayoralty,24,MISCELLANEOUS,18.0,...,00859,SUNDRIES,HEALTH STABILIZATION PAYMENT,59064200,59064200,2017,59605700,0,0,0
655,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,TECHNICAL ASSISTANCE FUND,0,0,2017,18000000,0,0,0
855,2016 11 17,2017,Federal Grants,33,Social Services - Federal,71.0,Department of Homeless Services,25,Federal Grants-Categorical,214.0,...,00923,EMERGENCY SHELTER GRANTS PROGRAM,EMERGENCY SHELTER,0,15147030,2017,15147030,0,0,0
863,2016 11 17,2017,Federal Grants,33,Social Services - Federal,71.0,Department of Homeless Services,25,Federal Grants-Categorical,293.0,...,11958,TANF--EMERGENCY ASSISTANCE,TANF EMERGENCY ASSISTANCE,661493,661493,2017,26030814,661493,661493,661493
882,2016 11 17,2017,Federal Grants,35,Other - Federal,2.0,Mayoralty,25,Federal Grants-Categorical,297.0,...,03264,HAZARD MITIGATION GRANT,HAZARD MITIGATION GRANT (HMGP),0,15533624,2017,15533624,0,0,0

In [10]:
result1 = (MainDF["Revenue Source Name"] == "HEALTH RESEARCH") & ~(MainDF["Agency Name"] == "Department of Homeless Services")
MainDF[result1].head()

,Publication Date,Fiscal Year,Fundind Source Name,FPS Group,FPS Group Name,Agency Number,Agency Name,Revenue Category,Revenue Category Name,Revenue Class Code,...,Revenue Source,Revenue Source Name,Revenue Structure Description,Adopted Budget Amount,Current Modified Budget Amount,Yr1_FY,Year 1 Revenue Amount,Year 2 Revenue Amount,Year 3 Revenue Amount,Year 4 Revenue Amount
642,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,NEIGHBORHOOD HEALTH HUBS,0,4369,2017,4369,0,0,0
643,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,NON-NHAC HUB REVENUE,0,16666,2017,16666,0,0,0
644,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,RWJ DASH GRANT,0,8000,2017,8000,613,0,0
645,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,MERCK FOR MOTHER'S PROGRAM - FPHNY,0,5300,2017,5300,0,0,0
646,2016 11 17,2017,Other Categorical Grants,30,Other Categorical Grants,816.0,Department of Health and Mental Hygiene,27,Non-Governmental Grants,36.0,...,37941,HEALTH RESEARCH,MINORITY HEALTH,0,14479,2017,14479,0,0,0

## Sort on column

In [11]:
selected_rows = [MainDF["Fiscal Year"] == 2018]
sorted_rows = selected_rows.sort_values("Year 1 Revenue Amount", ascending=False)
print(sorted_rows[["Revenue Source Name", "Adopted Budget Amount"]].head())

AttributeError: 'list' object has no attribute 'sort_values'

## [MainDF["Fiscal Year"] == 2018] ==== List
## MainDF[MainDF["Fiscal Year"] == 2018] === Dataframe

In [ ]:
selected_rows = MainDF[MainDF["Fiscal Year"] == 2018]
sorted_rows = selected_rows.sort_values("Year 1 Revenue Amount", ascending=False)
print(sorted_rows[["Revenue Source Name", "Adopted Budget Amount"]].head())

## ØªÙ…Ø±ÛŒÙ†...Ù…ÛŒØ§Ù†Ú¯ÛŒÙ† Ø¯Ø±Ø¢Ù…Ø¯ Ø³Ø§Ù„ Ø§ÙˆÙ„ Ùˆ Ø¯ÙˆÙ… Ùˆ Ø³ÙˆÙ… Ø´Ø±Ú©ØªÙ‡Ø§ÛŒÛŒ Ú©Ù‡ Ø±ÙˆÛŒ Ù…Ø­ØµÙˆÙ„Ø§Øª Ø³Ù„Ø§Ù…Øª ØªØ­Ù‚ÛŒÙ‚Ø§Øª Ù…ÛŒÚ©Ù†Ù†Ø¯ Ø±Ø§ Ø¨Ø¯Ø³Øª Ø¢ÙˆØ±Ø¯ÛŒØ¯.
## Ø¯Ø±Ø¢Ù…Ø¯ Ø³Ø§Ù„Ø§Ù†Ù‡ Ø§ÛŒÙ† Ø´Ø±Ú©Øª Ù‡Ø§Ø±Ø§ Ø§Ø² Ø¨ÙˆØ¯Ø¬Ù‡ ØªØ®ØµÛŒØµ Ø¯Ø§Ø¯Ù‡ Ø´Ø¯Ù‡ Ú©Ù… Ú©Ù†ÛŒØ¯ Ùˆ Ù…Ø¬Ø¯Ø¯ Ù…ÛŒØ§Ù†Ú¯ÛŒÙ† Ø¨Ú¯ÛŒØ±ÛŒØ¯.
## Year 1 Revenue Amount, Revenue Source Name = "HEALTH RESEARCH"
## Ú©Ø¯Ø§Ù… Ù…Ù†Ø¨Ø¹ Ø¯Ø±Ø¢Ù…Ø¯ÛŒØŒ Ø¨ÛŒØ´ØªØ±ÛŒÙ† Ø¯Ø±Ø¢Ù…Ø¯ Ø±Ø§ Ø¯Ø± Ù…Ø¬Ù…ÙˆØ¹ Ø³Ù‡ Ø³Ø§Ù„ Ø§ÙˆÙ„ Ø¯Ø§Ø´ØªÙ‡ Ø§Ø³Øª